In [42]:
import tensorflow as tf 
import keras 
from keras.layers import Dense 
import pandas as pd 
import numpy as np 

In [43]:
df  = pd.read_csv('Iris.csv')
df_shuffled = df.sample(frac=1,random_state=42).reset_index(drop=True)
input_training_data = df_shuffled.loc[0:100,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
output_training_data = df_shuffled.loc[0:100,['Species']]

input_testing_data = df_shuffled.loc[101:150,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
output_testing_data = df_shuffled.loc[101:150,['Species']]

In [44]:
x_train = input_training_data.to_numpy()
y_train = pd.get_dummies(output_training_data,columns=['Species'],dtype= int)
y_train = y_train.to_numpy()
x_test = input_testing_data.to_numpy()
y_test = pd.get_dummies(output_testing_data,columns=['Species'],dtype=int)
y_test = y_test.to_numpy()
w1 = np.random.rand(3,4)
w2 = np.random.rand(3,3)
b1 = np.random.rand()
b2 = np.random.rand()
print(f" x_train = {x_train.shape} y_train = {y_train.shape}")


 x_train = (101, 4) y_train = (101, 3)


In [45]:
model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(Dense(5,activation = 'relu' ))
model.add(Dense(5,activation='relu'))
model.add(Dense(3,activation='softmax'))


In [46]:
model.compile(optimizer='adam',loss = 'categorical_crossentropy', metrics=['accuracy'])

In [47]:
model.fit(x_train,y_train , epochs = 900 , batch_size=32,validation_split=0.2 )

Epoch 1/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 131ms/step - accuracy: 0.2539 - loss: 1.8300 - val_accuracy: 0.2381 - val_loss: 1.7297
Epoch 2/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.2578 - loss: 1.7678 - val_accuracy: 0.2381 - val_loss: 1.7040
Epoch 3/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.2188 - loss: 1.8586 - val_accuracy: 0.2381 - val_loss: 1.6786
Epoch 4/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.2734 - loss: 1.6666 - val_accuracy: 0.2381 - val_loss: 1.6543
Epoch 5/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.2461 - loss: 1.7520 - val_accuracy: 0.2381 - val_loss: 1.6303
Epoch 6/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.2930 - loss: 1.6475 - val_accuracy: 0.2381 - val_loss: 1.6058
Epoch 7/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.2656 - loss: 1.6698 - val_accuracy: 0.2381 - val_loss: 1.5810
Epoch 8/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.2602 - loss: 1.5797 - val_accuracy: 0.2857 - val_loss

In [48]:
# evaluate accuracy 
loss , accuracy = model.evaluate(x_test,y_test,verbose=0)
print(f"accuracy = {accuracy}")
 
# Make predictions 
predictions = model.predict(x_test)
print(predictions)

accuracy = 0.9795918464660645
1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/stepWARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002A425E6FCE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[9.01909113e-01 6.68498203e-02 3.12410425e-02]
 [9.01909113e-01 6.68498203e-02 3.12410425e-02]
 [1.51407349e-08 2.33865961e-01 7.66134083e-01]
 [1.44676155e-12 8.936572

In [50]:
# Get the index of max value in each row
max_indices = np.argmax(predictions, axis=1)

# Convert to one-hot encoded array
one_hot_predictions = np.eye(predictions.shape[1])[max_indices]

print(one_hot_predictions)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
y_test

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])