In [1]:
import tensorflow as tf 
import keras 
from keras.layers import Dense 
import pandas as pd 
import numpy as np 


In [2]:

df  = pd.read_csv('Iris.csv')
df_shuffled = df.sample(frac=1,random_state=42).reset_index(drop=True)
input_training_data = df_shuffled.loc[0:100,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
output_training_data = df_shuffled.loc[0:100,['Species']]


In [3]:

input_testing_data = df_shuffled.loc[101:150,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
output_testing_data = df_shuffled.loc[101:150,['Species']]
x_train = input_training_data.to_numpy()
y_train = pd.get_dummies(output_training_data,columns=['Species'],dtype= int)
y_train = y_train.to_numpy()
x_test = input_testing_data.to_numpy()
y_test = pd.get_dummies(output_testing_data,columns=['Species'],dtype=int)
y_test = y_test.to_numpy()


In [4]:

w1 = np.random.rand(3,4)
w2 = np.random.rand(3,3)
b1 = np.random.rand()
b2 = np.random.rand()
print(f" x_train = {x_train.shape} y_train = {y_train.shape}")


 x_train = (101, 4) y_train = (101, 3)


In [5]:

model = keras.Sequential()
model.add(keras.Input(shape=(4,)))
model.add(Dense(5,activation = 'relu' ))
model.add(Dense(5,activation='relu'))
model.add(Dense(3,activation='softmax'))


In [6]:

model.compile(optimizer='adam',loss = 'categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train,y_train , epochs = 900 , batch_size=32,validation_split=0.2 )


Epoch 1/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 98ms/step - accuracy: 0.3867 - loss: 1.0556 - val_accuracy: 0.3810 - val_loss: 1.0578
Epoch 2/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3633 - loss: 1.0552 - val_accuracy: 0.3810 - val_loss: 1.0548
Epoch 3/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3438 - loss: 1.0559 - val_accuracy: 0.3810 - val_loss: 1.0518
Epoch 4/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3469 - loss: 1.0512 - val_accuracy: 0.3810 - val_loss: 1.0487
Epoch 5/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3945 - loss: 1.0405 - val_accuracy: 0.3810 - val_loss: 1.0455
Epoch 6/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4102 - loss: 1.0334 - val_accuracy: 0.3810 - val_loss: 1.0425
Epoch 7/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3828 - loss: 1.0368 - val_accuracy: 0.3810 - val_loss: 1.0396
Epoch 8/900
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3672 - loss: 1.0350 - val_accuracy: 0.3810 - val_loss:

In [7]:

# evaluate accuracy 
loss , accuracy = model.evaluate(x_test,y_test,verbose=0)
print(f"accuracy = {accuracy}")
 
# Make predictions 
predictions = model.predict(x_test)

# Get the index of max value in each row
max_indices = np.argmax(predictions, axis=1)

# Convert to one-hot encoded array
one_hot_predictions = np.eye(predictions.shape[1])[max_indices]

print(one_hot_predictions)


accuracy = 0.9795918464660645
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:

y_test

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])